# Generated by Django 2.2.16 on 2023-05-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230501_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Введите текст поста', verbose_name='дата публикации'),
        ),
    ]
