# Generated by Django 2.2.16 on 2023-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20230512_1237'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_follow'),
        ),
    ]
